## This configuration was generated by terraform-provider-oci

resource oci_apigateway_gateway export_testimonials {
  #certificate_id = <<Optional value not found in discovery>>
  compartment_id = var.compartment_ocid
  display_name  = "${var.project_name}"
  endpoint_type = "PUBLIC"
  freeform_tags = {
  }
  network_security_group_ids = [
  ]
  response_cache_details {
    #authentication_secret_id = <<Optional value not found in discovery>>
    #authentication_secret_version_number = <<Optional value not found in discovery>>
    #connect_timeout_in_ms = <<Optional value not found in discovery>>
    #is_ssl_enabled = <<Optional value not found in discovery>>
    #is_ssl_verify_disabled = <<Optional value not found in discovery>>
    #read_timeout_in_ms = <<Optional value not found in discovery>>
    #send_timeout_in_ms = <<Optional value not found in discovery>>
    #servers = <<Optional value not found in discovery>>
    type = "NONE"
  }
  subnet_id = oci_core_subnet.export_project-public.id
}

resource oci_apigateway_deployment export_testimonials {
  compartment_id = var.compartment_ocid
  display_name  = "${var.project_name}"
  freeform_tags = {
  }
  gateway_id  = oci_apigateway_gateway.export_testimonials.id
  path_prefix = "/"
  specification {
    logging_policies {
      #access_log = <<Optional value not found in discovery>>
      #execution_log {
      #  #is_enabled = <<Optional value not found in discovery>>
      #  log_level = "INFO"
      #}
    }
    request_policies {
      authentication {
        #audiences = <<Optional value not found in discovery>>
        cache_key = [
        ]
        function_id                 = oci_functions_function.export_project_2_2.id
        is_anonymous_access_allowed = "true"
        #issuers = <<Optional value not found in discovery>>
        #max_clock_skew_in_seconds = <<Optional value not found in discovery>>
        parameters = {
        }
        #public_keys = <<Optional value not found in discovery>>
        #token_auth_scheme = <<Optional value not found in discovery>>
        token_header = "Cookie"
        #token_query_param = <<Optional value not found in discovery>>
        type = "CUSTOM_AUTHENTICATION"
        #validation_failure_policy = <<Optional value not found in discovery>>
        #validation_policy = <<Optional value not found in discovery>>
        #verify_claims = <<Optional value not found in discovery>>
      }
      cors {
        allowed_headers = [
          "",
        ]
        allowed_methods = [
          "*",
        ]
        allowed_origins = [
          "*",
        ]
        exposed_headers = [
        ]
        is_allow_credentials_enabled = "true"
        max_age_in_seconds           = "0"
      }
      #dynamic_authentication = <<Optional value not found in discovery>>
      mutual_tls {
        allowed_sans = [
        ]
        is_verified_certificate_required = "false"
      }
      #rate_limiting = <<Optional value not found in discovery>>
      #usage_plans = <<Optional value not found in discovery>>
    }
    routes {
      backend {
        #allowed_post_logout_uris = <<Optional value not found in discovery>>
        #body = <<Optional value not found in discovery>>
        #connect_timeout_in_seconds = <<Optional value not found in discovery>>
        function_id = oci_functions_function.export_project_2_1.id
        #headers = <<Optional value not found in discovery>>
        #is_ssl_verify_disabled = <<Optional value not found in discovery>>
        #post_logout_state = <<Optional value not found in discovery>>
        #read_timeout_in_seconds = <<Optional value not found in discovery>>
        #routing_backends = <<Optional value not found in discovery>>
        #selection_source = <<Optional value not found in discovery>>
        #send_timeout_in_seconds = <<Optional value not found in discovery>>
        #status = <<Optional value not found in discovery>>
        type = "ORACLE_FUNCTIONS_BACKEND"
        #url = <<Optional value not found in discovery>>
      }
      logging_policies {
        #access_log = <<Optional value not found in discovery>>
        execution_log {
          #is_enabled = <<Optional value not found in discovery>>
          log_level = ""
        }
      }
      methods = [
        "GET",
        "POST",
      ]
      path = "/testimonial"
      request_policies {
        authorization {
          #allowed_scope = <<Optional value not found in discovery>>
          type = "AUTHENTICATION_ONLY"
        }
        #body_validation = <<Optional value not found in discovery>>
        #cors = <<Optional value not found in discovery>>
        #header_transformations = <<Optional value not found in discovery>>
        #header_validations = <<Optional value not found in discovery>>
        #query_parameter_transformations = <<Optional value not found in discovery>>
        #query_parameter_validations = <<Optional value not found in discovery>>
        #response_cache_lookup = <<Optional value not found in discovery>>
      }
      response_policies {
        #header_transformations = <<Optional value not found in discovery>>
        #response_cache_store = <<Optional value not found in discovery>>
      }
    }
    routes {
      backend {
        #allowed_post_logout_uris = <<Optional value not found in discovery>>
        #body = <<Optional value not found in discovery>>
        #connect_timeout_in_seconds = <<Optional value not found in discovery>>
        function_id = oci_functions_function.export_project_2_1.id
        #headers = <<Optional value not found in discovery>>
        #is_ssl_verify_disabled = <<Optional value not found in discovery>>
        #post_logout_state = <<Optional value not found in discovery>>
        #read_timeout_in_seconds = <<Optional value not found in discovery>>
        #routing_backends = <<Optional value not found in discovery>>
        #selection_source = <<Optional value not found in discovery>>
        #send_timeout_in_seconds = <<Optional value not found in discovery>>
        #status = <<Optional value not found in discovery>>
        type = "ORACLE_FUNCTIONS_BACKEND"
        #url = <<Optional value not found in discovery>>
      }
      logging_policies {
        #access_log = <<Optional value not found in discovery>>
        #execution_log {
        #  #is_enabled = <<Optional value not found in discovery>>
        #  log_level = ""
        #}
      }
      methods = [
        "GET",
        "POST",
      ]
      path = "/welcome"
      request_policies {
        authorization {
          #allowed_scope = <<Optional value not found in discovery>>
          type = "ANONYMOUS"
        }
        #body_validation = <<Optional value not found in discovery>>
        #cors = <<Optional value not found in discovery>>
        #header_transformations = <<Optional value not found in discovery>>
        #header_validations = <<Optional value not found in discovery>>
        #query_parameter_transformations = <<Optional value not found in discovery>>
        #query_parameter_validations = <<Optional value not found in discovery>>
        #response_cache_lookup = <<Optional value not found in discovery>>
      }
      response_policies {
        #header_transformations = <<Optional value not found in discovery>>
        #response_cache_store = <<Optional value not found in discovery>>
      }
    }
    routes {
      backend {
        #allowed_post_logout_uris = <<Optional value not found in discovery>>
        #body = <<Optional value not found in discovery>>
        #connect_timeout_in_seconds = <<Optional value not found in discovery>>
        function_id = oci_functions_function.export_project_2_2.id
        #headers = <<Optional value not found in discovery>>
        #is_ssl_verify_disabled = <<Optional value not found in discovery>>
        #post_logout_state = <<Optional value not found in discovery>>
        #read_timeout_in_seconds = <<Optional value not found in discovery>>
        #routing_backends = <<Optional value not found in discovery>>
        #selection_source = <<Optional value not found in discovery>>
        #send_timeout_in_seconds = <<Optional value not found in discovery>>
        #status = <<Optional value not found in discovery>>
        type = "ORACLE_FUNCTIONS_BACKEND"
        #url = <<Optional value not found in discovery>>
      }
      logging_policies {
        #access_log = <<Optional value not found in discovery>>
        execution_log {
          #is_enabled = <<Optional value not found in discovery>>
          log_level = ""
        }
      }
      methods = [
        "GET",
        "POST",
      ]
      path = "/login"
      request_policies {
        authorization {
          #allowed_scope = <<Optional value not found in discovery>>
          type = "ANONYMOUS"
        }
        #body_validation = <<Optional value not found in discovery>>
        #cors = <<Optional value not found in discovery>>
        #header_transformations = <<Optional value not found in discovery>>
        #header_validations = <<Optional value not found in discovery>>
        #query_parameter_transformations = <<Optional value not found in discovery>>
        #query_parameter_validations = <<Optional value not found in discovery>>
        #response_cache_lookup = <<Optional value not found in discovery>>
      }
      response_policies {
        #header_transformations = <<Optional value not found in discovery>>
        #response_cache_store = <<Optional value not found in discovery>>
      }
    }
  }
}
