## This configuration was generated by terraform-provider-oci

resource oci_functions_application export_project_1 {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  config = {
    "COMPARTMENT_OCID"  = var.compartment_ocid
    "APP_URL"           = "https:// .apigateway.${var.region}.oci.customer-oci.com/testimonial"
    "AUTH_URL"          = "https:// .apigateway.${var.region}.oci.customer-oci.com/login"
    "SIGNUP_URL"        = "https:// .apigateway.${var.region}.oci.customer-oci.com/welcome?action=signup"
    "WELCOME_URL"       = "https:// .apigateway.${var.region}.oci.customer-oci.com/welcome"
    "CAROUSEL_PAGE_URL" = "https://objectstorage.${var.region}.oraclecloud.com/n/${data.oci_objectstorage_namespace.tenancy_namespace.namespace}/b/pub/o/login_carousel.html"
    "PAGE_URL"          = "https://objectstorage.${var.region}.oraclecloud.com/n/${data.oci_objectstorage_namespace.tenancy_namespace.namespace}/b/pub/o/testimonial.html"
    "SIGNUP_PAGE_URL"   = "https://objectstorage.${var.region}.oraclecloud.com/n/${data.oci_objectstorage_namespace.tenancy_namespace.namespace}/b/pub/o/login.html"
    "GENAI_ENDPOINT"    = "https://inference.generativeai.${var.region}.oci.oraclecloud.com"
    "GENAI_OCID"        = "ocid1.generativeaimodel.oc1.${var.region}...."
    "IDCS_URL"          = "idcs-"
    "DB_URL"            = ""
    "DB_USER"           = "admin"
    "DB_PASSWORD"       = ""
    "CLIENT_ID"         = ""
    "CLIENT_SECRET"     = ""
    "PROFILE_ID"        = ""
  }
  display_name = "${var.project_name}"
  freeform_tags = {
  }
  network_security_group_ids = [
  ]
  shape = "GENERIC_X86"
  subnet_ids = [
    oci_core_subnet.export_project-private.id,
  ]
  syslog_url = ""
  trace_config {
    domain_id  = ""
    is_enabled = "false"
  }
}

resource oci_functions_function export_project_2_1 {
  application_id = oci_functions_application.export_project_1.id
  config = {
  }
  display_name = "${var.image_name_testimonials}"
  freeform_tags = {
  }
  image         = "${var.registry}/${data.oci_objectstorage_namespace.tenancy_namespace.namespace}/${var.image_name_testimonials}:1"
  #image_digest  = 
  memory_in_mbs = "512"
  provisioned_concurrency_config {
    #count = <<Optional value not found in discovery>>
    strategy = "NONE"
  }
  timeout_in_seconds = "30"
  trace_config {
    is_enabled = "false"
  }
  depends_on = [oci_artifacts_container_repository.export_project_1]
}

resource oci_functions_function export_project_2_2 {
  application_id = oci_functions_application.export_project_1.id
  config = {
  }
  display_name = "${var.image_name_authorizer}"
  freeform_tags = {
  }
  image         = "${var.registry}/${data.oci_objectstorage_namespace.tenancy_namespace.namespace}/${var.image_name_authorizer}:1"
  #image_digest  = 
  memory_in_mbs = "512"
  provisioned_concurrency_config {
    #count = <<Optional value not found in discovery>>
    strategy = "NONE"
  }
  timeout_in_seconds = "30"
  trace_config {
    is_enabled = "false"
  }
  depends_on = [oci_artifacts_container_repository.export_project_2]
}
