## This configuration was generated by terraform-provider-oci

resource oci_core_subnet export_project-private {
  #availability_domain = <<Optional value not found in discovery>>
  cidr_block     = "10.0.1.0/24"
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  #dhcp_options_id = <<Optional value not found in discovery>>
  display_name    = "${var.project_name}-private"
  #dns_label = <<Optional value not found in discovery>>
  freeform_tags = {
  }
  #ipv6cidr_block = <<Optional value not found in discovery>>
  ipv6cidr_blocks = [
  ]
  prohibit_internet_ingress  = "true"
  prohibit_public_ip_on_vnic = "true"
  route_table_id             = oci_core_route_table.export_Route-Table-for-project.id
  security_list_ids = [
    oci_core_default_security_list.export_Default-Security-List-for-project.id,
  ]
  vcn_id = oci_core_vcn.export_project_3.id
}

resource "oci_core_subnet" export_project-public {
  cidr_block          = "10.0.0.0/24"
  compartment_id      = oci_artifacts_container_configuration.export_container_configuration.id
  display_name        = "${var.project_name}-public"
  freeform_tags       = {
  }
  prohibit_internet_ingress  = "false"
  prohibit_public_ip_on_vnic = "false"
  route_table_id             = oci_core_default_route_table.export_Default-Route-Table-for-project.id
  security_list_ids = [
    oci_core_default_security_list.export_Default-Security-List-for-project.id,
  ]
  vcn_id = oci_core_vcn.export_project_3.id
}

resource oci_core_default_security_list export_Default-Security-List-for-project {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  
  display_name = "Default Security List for ${var.project_name}"
  egress_security_rules {
    #description = <<Optional value not found in discovery>>
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "all"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  freeform_tags = {
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "22"
      min = "22"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "4"
      type = "3"
    }
    protocol    = "1"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "-1"
      type = "3"
    }
    protocol    = "1"
    source      = "10.0.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    protocol = "6" # TCP
    source = "0.0.0.0/0"
    tcp_options {
      min = 443
      max = 443
    }
    description = "Allow APIGW HTTPS traffic"
  }
  manage_default_resource_id = oci_core_vcn.export_project_3.default_security_list_id
}

resource oci_core_vcn export_project_3 {
  #byoipv6cidr_details = <<Optional value not found in discovery>>
  #cidr_block = <<Optional value not found in discovery>>
  cidr_blocks = [
    "10.0.0.0/16",
  ]
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  
  display_name = "${var.project_name}"
  #dns_label = <<Optional value not found in discovery>>
  freeform_tags = {
  }
  ipv6private_cidr_blocks = [
  ]
  #is_ipv6enabled = <<Optional value not found in discovery>>
  #is_oracle_gua_allocation_enabled = <<Optional value not found in discovery>>
  security_attributes = {
  } 
}

resource oci_core_default_route_table export_Default-Route-Table-for-project {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  display_name = "Default Route Table for ${var.project_name} public subnet"
  freeform_tags = {
  }
  manage_default_resource_id = oci_core_vcn.export_project_3.default_route_table_id
  route_rules {
    description = "Internet Gateway"
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_internet_gateway.export_project-internet-gw.id
  }
}

resource oci_core_route_table export_Route-Table-for-project {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  display_name = "Route Table for ${var.project_name} private subnet"
  freeform_tags = {
  }
  #manage_default_resource_id = oci_core_vcn.export_project_3.default_route_table_id
  route_rules {
    #description = <<Optional value not found in discovery>>
    destination       = "all-fra-services-in-oracle-services-network"
    destination_type  = "SERVICE_CIDR_BLOCK"
    network_entity_id = oci_core_service_gateway.export_svc-gw.id
    #route_type = <<Optional value not found in discovery>>
  }
  vcn_id = oci_core_vcn.export_project_3.id
}

data "oci_core_services" "all_oci_services" {
  filter {
    name   = "name"
    values = ["All .* Services In Oracle Services Network"]
    regex  = true
  }
  count = 1
}

resource oci_core_service_gateway export_svc-gw {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  
  display_name = "${var.project_name}-svc-gw"
  freeform_tags = {
  }
  #route_table_id = <<Optional value not found in discovery>>
  services {
    service_id = lookup(data.oci_core_services.all_oci_services[0].services[0], "id")
  }
  vcn_id = oci_core_vcn.export_project_3.id
}

resource oci_core_internet_gateway export_project-internet-gw {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  display_name = "Internet Gateway"
  enabled      = "true"
  freeform_tags = {
  }
  vcn_id = oci_core_vcn.export_project_3.id
}
